name: CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.12"]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov mypy flake8
        # Install project dependencies
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f async-chat-stream_2_main_v1.0/requirements.txt ]; then 
          pip install -r async-chat-stream_2_main_v1.0/requirements.txt
        fi
        
    - name: Run tests with coverage
      run: |
        pytest --cov=./ --cov-report=xml || true  # Don't fail on missing tests
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      continue-on-error: true  # Don't fail if coverage upload fails
        
    - name: Type checking
      run: |
        mypy . || true  # Don't fail on type errors during development
        
    - name: Lint
      run: |
        flake8 . --max-line-length=100 --exclude=venv/*,.git/* || true  # Don't fail on lint errors during development