name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          
      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          
      - name: Update dependencies
        run: |
          pip-compile --upgrade requirements.in
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'build(deps): update dependencies'
          title: 'build(deps): update dependencies'
          body: 'Updated dependencies to their latest versions'
          branch: 'build/update-dependencies'
          base: 'development' 