name: Documentation

on:
  push:
    branches: [ main, development ]
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/markdown-link-check.json' 