name: Security Scan

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f async-chat-stream_2_main_v1.0/requirements.txt ]; then 
            pip install -r async-chat-stream_2_main_v1.0/requirements.txt
          fi
          
      - name: Run Bandit
        run: bandit -r . -ll -ii || true  # Don't fail during development
        
      - name: Check dependencies
        run: safety check || true  # Don't fail during development